/*
    This file is part of OpenRRCP

    OpenRRCP is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    OpenRRCP is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with OpenRRCP; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

    ---

    You can send your updates, patches and suggestions on this software
    to it's original author, Andrew Chernyak (nording@yandex.ru)
    This would be appreciated, however not required.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../lib/libcli.h"
#include "rrcp_cli.h"
#include "rrcp_switches.h"
#include "rrcp_io.h"
#include "rrcp_config.h"

int cmd_show_version(struct cli_def *cli, char *command, char *argv[], int argc)
{
    cli_print(cli, "OpenRRCP CLI, Version %s",RRCP_CLI_VERSION);
    cli_print(cli, "http://openrrcp.org.ru/");
    cli_print(cli, "Licensed under terms of GPL");
    cli_print(cli, "http://www.gnu.org/licenses/gpl.html#SEC1\n");

    cli_print(cli, "%d FastEthernet/IEEE 802.3 interface(s)",switchtypes[switchtype].num_ports >24 ? 24 : switchtypes[switchtype].num_ports);
    if (switchtypes[switchtype].num_ports >24){
	cli_print(cli, "%d Gigabit Ethernet/IEEE 802.3 interface(s)\n",switchtypes[switchtype].num_ports >24 ? switchtypes[switchtype].num_ports-24 : 0);
    }

    cli_print(cli, "\nBase ethernet MAC Address:  %02x:%02x:%02x:%02x:%02x:%02x",
		    dest_mac[0],
		    dest_mac[1],
		    dest_mac[2],
		    dest_mac[3],
		    dest_mac[4],
		    dest_mac[5]);
    cli_print(cli, "Vendor: %s",switchtypes[switchtype].vendor);
    cli_print(cli, "Model: %s",switchtypes[switchtype].model);
    cli_print(cli, "Chip: %s",chipnames[switchtypes[switchtype].chip_id]);
    cli_print(cli, "802.1Q support: %s",(switchtypes[switchtype].chip_id==rtl8316b) ? "Yes" : "No/Buggy");
    cli_print(cli, "Facing host interface: %s",ifname);
    return CLI_OK;
}

int cmd_show_config(struct cli_def *cli, char *command, char *argv[], int argc)
{
    char text[32768];

    cli_print(cli, "!");
    cli_print(cli, "! Config for %s %s switch at %02x:%02x:%02x:%02x:%02x:%02x@%s",
		    switchtypes[switchtype].vendor,
		    switchtypes[switchtype].model,
		    dest_mac[0],
		    dest_mac[1],
		    dest_mac[2],
		    dest_mac[3],
		    dest_mac[4],
		    dest_mac[5],
		    ifname);
    cli_print(cli, "! generated by OpenRRCP CLI ver %s",RRCP_CLI_VERSION);
    rrcp_config_bin2text(text,sizeof(text),(strcasecmp(command,"show running-config full")==0));
    cli_print(cli, "%s", text);
    return CLI_OK;
}

int cmd_test(struct cli_def *cli, char *command, char *argv[], int argc)
{
    int i;
    cli_print(cli, "called %s with \"%s\"", __FUNCTION__, command);
    cli_print(cli, "%d arguments:", argc);
    for (i = 0; i < argc; i++)
    {
	cli_print(cli, "	%s", argv[i]);
    }
    return CLI_OK;
}

void cmd_show_register_commands(struct cli_def *cli)
{
    struct cli_command *c,*c2;
    c = cli_register_command(cli, NULL, "show", NULL,  PRIVILEGE_UNPRIVILEGED, MODE_EXEC, "Show running system information");
    cli_register_command(cli, c, "version", cmd_show_version, PRIVILEGE_UNPRIVILEGED, MODE_EXEC, "System hardware and software status");
    cli_register_command(cli, c, "configuration", cmd_test, PRIVILEGE_PRIVILEGED, MODE_EXEC, "Contents of Non-Volatile memory");
    c2 = cli_register_command(cli, c, "running-config", cmd_show_config, PRIVILEGE_PRIVILEGED, MODE_EXEC, "Current operating configuration");
    cli_register_command(cli, c2, "full", cmd_show_config, PRIVILEGE_PRIVILEGED, MODE_EXEC, "Current operating configuration including default statements");
    cli_register_command(cli, c, "startup-config", cmd_test, PRIVILEGE_PRIVILEGED, MODE_EXEC, "Contents of startup configuration");
}
