/*
    This file is part of OpenRRCP

    OpenRRCP is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    OpenRRCP is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with OpenRRCP; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

    ---

    You can send your updates, patches and suggestions on this software
    to it's original author, Andrew Chernyak (nording@yandex.ru)
    This would be appreciated, however not required.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../lib/libcli.h"
#include "rrcp_cli.h"
#include "rrcp_switches.h"
#include "rrcp_io.h"
#include "rrcp_config.h"


int cmd_show_ip_igmp_snooping(struct cli_def *cli, char *command, char *argv[], int argc)
{
    if (argc>0){
	if (strcmp(argv[0],"?")==0){
	    cli_print(cli, "  |  Output modifiers");
	    cli_print(cli, "  <cr>");
	}else{
	    cli_print(cli, "%% Invalid input detected.");
	}
    }else{
	if (strcasecmp(command,"show ip igmp snooping")==0){
	    cli_print(cli, "Global IGMP Snooping configuration:");
	    cli_print(cli, "-----------------------------------");
	    cli_print(cli, "IGMP snooping              : %s",swconfig.alt_igmp_snooping.config.en_igmp_snooping ? "Enabled":"Disabled");
	}
	if (strcasecmp(command,"show ip igmp snooping mrouter")==0){
	    int port,port_phys;
	    char pn[64];

	    cli_print(cli, "Multicast routers found on port(s):");
	    for(port=1;port<=switchtypes[switchtype].num_ports;port++){
	        port_phys=map_port_number_from_logical_to_physical(port);
	        if (swconfig.alt_mrouter_mask.mask & (1<<port_phys)){
		    cli_print(cli, "%s",rrcp_config_get_portname(pn,sizeof(pn),port,port_phys));
		}
	    }
	}
    }
    return CLI_OK;
}

int cmd_write_terminal(struct cli_def *cli, char *command, char *argv[], int argc)
{
    char text[32768];

    cli_print(cli, "!");
    cli_print(cli, "! Config for %s %s switch at %02x:%02x:%02x:%02x:%02x:%02x@%s",
                    switchtypes[switchtype].vendor,
                    switchtypes[switchtype].model,
                    dest_mac[0],
                    dest_mac[1],
                    dest_mac[2],
                    dest_mac[3],
                    dest_mac[4],
                    dest_mac[5],
                    ifname);
    cli_print(cli, "! generated by OpenRRCP CLI ver %s",RRCP_CLI_VERSION);
    rrcp_config_bin2text(text,sizeof(text),1);
    cli_print(cli, "%s", text);
    return CLI_OK;
}

int cmd_test(struct cli_def *cli, char *command, char *argv[], int argc)
{
    int i;
    cli_print(cli, "called %s with \"%s\"", __FUNCTION__, command);
    cli_print(cli, "%d arguments:", argc);
    for (i = 0; i < argc; i++)
    {
	cli_print(cli, "	%s", argv[i]);
    }
    return CLI_OK;
}

void cmd_other_register_commands(struct cli_def *cli)
{
    struct cli_command *c;
    c = cli_register_command(cli, NULL, "write", NULL,  PRIVILEGE_UNPRIVILEGED, MODE_EXEC, "Write running configuration to memory or terminal");
    cli_register_command(cli, c, "memory", cmd_write_memory, PRIVILEGE_UNPRIVILEGED, MODE_EXEC, "Write to NV memory");
    cli_register_command(cli, c, "terminal", cmd_write_terminal, PRIVILEGE_UNPRIVILEGED, MODE_EXEC, "Write to terminal");
}
