/*
    This file is part of OpenRRCP

    OpenRRCP is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    OpenRRCP is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with OpenRRCP; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

    ---

    You can send your updates, patches and suggestions on this software
    to it's original author, Andrew Chernyak (nording@yandex.ru)
    This would be appreciated, however not required.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../lib/libcli.h"
#include "rrcp_cli.h"
#include "rrcp_config.h"

int cmd_show_version(struct cli_def *cli, char *command, char *argv[], int argc)
{
    cli_print(cli, "OpenRRCP CLI ver %s",RRCP_CLI_VERSION);
    return CLI_OK;
}

int cmd_show_config(struct cli_def *cli, char *command, char *argv[], int argc)
{
    char text[32768];

//    rrcp_config_read_from_switch();
    cli_print(cli, "!");
    cli_print(cli, "! Config generated by OpenRRCP CLI ver %s",RRCP_CLI_VERSION);
    rrcp_config_bin2text(text,sizeof(text),0);
    cli_print(cli, "%s", text);
    return CLI_OK;
}

int cmd_test(struct cli_def *cli, char *command, char *argv[], int argc)
{
    int i;
    cli_print(cli, "called %s with \"%s\"", __FUNCTION__, command);
    cli_print(cli, "%d arguments:", argc);
    for (i = 0; i < argc; i++)
    {
	cli_print(cli, "	%s", argv[i]);
    }
    return CLI_OK;
}

void cmd_show_register_commands(struct cli_def *cli)
{
    struct cli_command *c;
    c = cli_register_command(cli, NULL, "show", NULL,  PRIVILEGE_UNPRIVILEGED, MODE_EXEC, "Show running system information");
    cli_register_command(cli, c, "version", cmd_show_version, PRIVILEGE_UNPRIVILEGED, MODE_EXEC, "System hardware and software status");
    cli_register_command(cli, c, "configuration", cmd_test, PRIVILEGE_PRIVILEGED, MODE_EXEC, "Contents of Non-Volatile memory");
    cli_register_command(cli, c, "running-config", cmd_show_config, PRIVILEGE_PRIVILEGED, MODE_EXEC, "Current operating configuration");
    cli_register_command(cli, c, "startup-config", cmd_test, PRIVILEGE_PRIVILEGED, MODE_EXEC, "Contents of startup configuration");
}
